controllers:
    resource: ../../src/Modules/*/Controller/*
    type: annotation
    prefix: /backend
    trailing_slash_on_root: false

kernel:
    resource: ../../src/Kernel.php
    type: annotation
